// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from 'react';

interface RegistryComponent {
  name: string;
  category: string;
  path: string;
  component: any;
}

export const registryIndex: Record<string, RegistryComponent> = {
  'button.signout': {
    name: 'button.signout',
    category: 'button',
    path: '#/registry/ui/button.signout.tsx',
    component: React.lazy(() => import('#/registry/ui/button.signout.tsx')),
  },
  'input.form-field': {
    name: 'input.form-field',
    category: 'input',
    path: '#/registry/ui/input.form-field.tsx',
    component: React.lazy(() => import('#/registry/ui/input.form-field.tsx')),
  },
  'button.theme': {
    name: 'button.theme',
    category: 'button',
    path: '#/registry/ui/button.theme.tsx',
    component: React.lazy(() => import('#/registry/ui/button.theme.tsx')),
  },
  'button.submit': {
    name: 'button.submit',
    category: 'button',
    path: '#/registry/ui/button.submit.tsx',
    component: React.lazy(() => import('#/registry/ui/button.submit.tsx')),
  },
  'radio.form-field': {
    name: 'radio.form-field',
    category: 'radio',
    path: '#/registry/ui/radio.form-field.tsx',
    component: React.lazy(() => import('#/registry/ui/radio.form-field.tsx')),
  },
  'select.form-field': {
    name: 'select.form-field',
    category: 'select',
    path: '#/registry/ui/select.form-field.tsx',
    component: React.lazy(() => import('#/registry/ui/select.form-field.tsx')),
  },
  'div.title-section': {
    name: 'div.title-section',
    category: 'div',
    path: '#/registry/ui/div.title-section.tsx',
    component: React.lazy(() => import('#/registry/ui/div.title-section.tsx')),
  },
  'skeleton.text': {
    name: 'skeleton.text',
    category: 'skeleton',
    path: '#/registry/ui/skeleton.text.tsx',
    component: React.lazy(() => import('#/registry/ui/skeleton.text.tsx')),
  },
  'hover.item': {
    name: 'hover.item',
    category: 'hover',
    path: '#/registry/ui/hover.item.tsx',
    component: React.lazy(() => import('#/registry/ui/hover.item.tsx')),
  },
  'dialog.confirmation': {
    name: 'dialog.confirmation',
    category: 'dialog',
    path: '#/registry/ui/dialog.confirmation.tsx',
    component: React.lazy(() => import('#/registry/ui/dialog.confirmation.tsx')),
  },
  'button.submit.loading.example': {
    name: 'button.submit.loading.example',
    category: 'button',
    path: '#/registry/examples/button.submit.loading.tsx',
    component: React.lazy(() => import('#/registry/examples/button.submit.loading.tsx')),
  },
  'button.signout.example': {
    name: 'button.signout.example',
    category: 'button',
    path: '#/registry/examples/button.signout.tsx',
    component: React.lazy(() => import('#/registry/examples/button.signout.tsx')),
  },
  'input.form-field.example': {
    name: 'input.form-field.example',
    category: 'input',
    path: '#/registry/examples/input.form-field.tsx',
    component: React.lazy(() => import('#/registry/examples/input.form-field.tsx')),
  },
  'button.theme.example': {
    name: 'button.theme.example',
    category: 'button',
    path: '#/registry/examples/button.theme.tsx',
    component: React.lazy(() => import('#/registry/examples/button.theme.tsx')),
  },
  'button.submit.example': {
    name: 'button.submit.example',
    category: 'button',
    path: '#/registry/examples/button.submit.tsx',
    component: React.lazy(() => import('#/registry/examples/button.submit.tsx')),
  },
  'radio.form-field.example': {
    name: 'radio.form-field.example',
    category: 'radio',
    path: '#/registry/examples/radio.form-field.tsx',
    component: React.lazy(() => import('#/registry/examples/radio.form-field.tsx')),
  },
  'select.form-field.example': {
    name: 'select.form-field.example',
    category: 'select',
    path: '#/registry/examples/select.form-field.tsx',
    component: React.lazy(() => import('#/registry/examples/select.form-field.tsx')),
  },
  'div.title-section.example': {
    name: 'div.title-section.example',
    category: 'div',
    path: '#/registry/examples/div.title-section.tsx',
    component: React.lazy(() => import('#/registry/examples/div.title-section.tsx')),
  },
  'skeleton.text.example': {
    name: 'skeleton.text.example',
    category: 'skeleton',
    path: '#/registry/examples/skeleton.text.tsx',
    component: React.lazy(() => import('#/registry/examples/skeleton.text.tsx')),
  },
  'hover.item.example': {
    name: 'hover.item.example',
    category: 'hover',
    path: '#/registry/examples/hover.item.tsx',
    component: React.lazy(() => import('#/registry/examples/hover.item.tsx')),
  },
  'dialog.confirmation.example': {
    name: 'dialog.confirmation.example',
    category: 'dialog',
    path: '#/registry/examples/dialog.confirmation.tsx',
    component: React.lazy(() => import('#/registry/examples/dialog.confirmation.tsx')),
  },
};
// [category]: { [key: registry/ui]: [key: registry/examples][] }
// TODO: Need to improve this structure
export const COMPONENT_CATEGORIES: Record<string, Record<string, string[]>>[] = {
  button: {
    'button.signout': ['button.signout'],
    'button.theme': ['button.theme'],
    'button.submit': ['button.submit.loading', 'button.submit'],
  },
  input: {
    'input.form-field': ['input.form-field'],
  },
  radio: {
    'radio.form-field': ['radio.form-field'],
  },
  select: {
    'select.form-field': ['select.form-field'],
  },
  div: {
    'div.title-section': ['div.title-section'],
  },
  skeleton: {
    'skeleton.text': ['skeleton.text'],
  },
  hover: {
    'hover.item': ['hover.item'],
  },
  dialog: {
    'dialog.confirmation': ['dialog.confirmation'],
  },
};
