import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const REGISTRY_UI_PATH = path.join(process.cwd(), 'registry', 'ui');
const REGISTRY_EXAMPLES_PATH = path.join(process.cwd(), 'registry', 'examples');
const _CONTENT_COMPONENTS_PATH = path.join(process.cwd(), 'content', 'components');

async function main() {
  let index = `// @ts-nocheck

/**
 * This file is autogenerated by @link https://github.com/plvo/shuip/blob/main/scripts/generate-registry.ts
 * Do not edit this file directly.
 */

import * as React from "react"

interface RegistryComponent {
    name: string;
    category: string;
    path: string;
    code: string;
    component: any;
}

export const registryIndex: Record<string, RegistryComponent> = {
`;

  const componentsCat: Record<string, Record<string, string[]>> = {};

  const registryUiFiles = fs.readdirSync(REGISTRY_UI_PATH);

  for (const file of registryUiFiles) {
    if (!file.endsWith('.tsx')) {
      continue;
    }

    const fullname: any = file.split('.tsx')[0];
    const category: any = fullname.split('.')[0];

    if (!componentsCat[category]) {
      componentsCat[category] = {};
    }

    componentsCat[category][fullname] = [];

    const fileContent = fs.readFileSync(path.join(REGISTRY_UI_PATH, file), 'utf-8');
    const { content } = matter(fileContent);

    index += `
    "${fullname}": {
      name: "${fullname}",
      category: "${category}",
      path: "#/registry/ui/${fullname}.tsx",
      code: ${JSON.stringify(content)},
      component: React.lazy(() => import("#/registry/ui/${fullname}.tsx")),
      },`;
  }

  const registryExamplesFiles = fs.readdirSync(REGISTRY_EXAMPLES_PATH);

  for (const file of registryExamplesFiles) {
    if (!file.endsWith('.tsx')) {
      continue;
    }

    const [fullname] = file.split('.tsx');
    const [category, name] = fullname.split('.');

    if (!componentsCat[category]) {
      componentsCat[category] = {};
    }
    componentsCat[category][`${category}.${name}`].push(fullname);

    const fileContent = fs.readFileSync(path.join(REGISTRY_EXAMPLES_PATH, file), 'utf-8');
    const { content } = matter(fileContent);

    index += `
    "${fullname}.example": {
      name: "${fullname}.example",
      category: "${category}",
      path: "#/registry/examples/${fullname}.tsx",
      code: ${JSON.stringify(content)},
      component: React.lazy(() => import("#/registry/examples/${fullname}.tsx")),
      },`;
  }

  index += '};';

  index += `
  /**
   * [category]: { [key: registry/ui]: [key: registry/examples][] } 
   * TODO: Need to improve this structure
   */ 
  export const COMPONENT_CATEGORIES:Record<string, Record<string, string[]>> = ${JSON.stringify(componentsCat, null, 2)};
  `;

  fs.writeFileSync('./registry/__index__.ts', index);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
