import fs from 'fs';
import path from 'path';

const REGISTRY_UI_PATH = path.join(process.cwd(), 'registry', 'ui');
const REGISTRY_EXAMPLES_PATH = path.join(process.cwd(), 'registry', 'examples');

async function main() {
  let index = `// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

interface RegistryComponent {
    name: string;
    category: string;
    path: string;
    component: any;
}

export const registryIndex: Record<string, RegistryComponent> = {
`;

  let componentsCat: Record<string, Record<string, string[]>> = {};

  const registryUiFiles = fs.readdirSync(REGISTRY_UI_PATH);

  for (const file of registryUiFiles) {
    if (!file.endsWith('.tsx')) {
      continue;
    }

    const fullname: any = file.split('.tsx')[0];
    const category: any = fullname.split('.')[0];

    if (!componentsCat[category]) {
      componentsCat[category] = {};
    }

    componentsCat[category][fullname] = [];

    index += `
    "${fullname}": {
      name: "${fullname}",
      category: "${category}",
      path: "#/registry/ui/${fullname}.tsx",
      component: React.lazy(() => import("#/registry/ui/${fullname}.tsx")),
      },`;
  }

  const registryExamplesFiles = fs.readdirSync(REGISTRY_EXAMPLES_PATH);

  for (const file of registryExamplesFiles) {
    if (!file.endsWith('.tsx')) {
      continue;
    }

    const [fullname] = file.split('.tsx');
    const [category, name] = fullname.split('.');

    if (!componentsCat[category]) {
      componentsCat[category] = {};
    }

    componentsCat[category][`${category}.${name}`].push(fullname);

    index += `
    "${fullname}.example": {
      name: "${fullname}.example",
      category: "${category}",
      path: "#/registry/examples/${fullname}.tsx",
      component: React.lazy(() => import("#/registry/examples/${fullname}.tsx")),
      },`;
  }

  index += '};';

  index += `
  // [category]: { [key: registry/ui]: [key: registry/examples][] } 
  // TODO: Need to improve this structure
  export const COMPONENT_CATEGORIES:Record<string, Record<string, string[]>> = ${JSON.stringify(componentsCat, null, 2)};
  `;

  fs.writeFileSync('./registry/__index__.ts', index);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
