name: Normalize PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  normalize:
    name: "🤖 Normalize PR Title"
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4

      - name: "⚡ Normalize PR Title"
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/normalize-pr-title.cjs');
            await script({ github, context, core });
